name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Clear npm cache
      run: npm cache clean --force
    - name: Install dependencies
      run: |
        cd /home/ubuntu/actions-runner/_work/Node-Express/Node-Express/Edu-Connect-API
        npm ci
    - name: Set up environment variables
      run: |
        cd /home/ubuntu/actions-runner/_work/Node-Express/Node-Express/Edu-Connect-API
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
