name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    defaults:
       run:
         working-directory: './Edu-Connect-API/'

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './Edu-Connect-API/package-lock.json'
        
    - name: Install dependencies
      run: npm ci
      working-directory: './Edu-Connect-API'
      
    - name: Set up environment variables
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
      working-directory: './Edu-Connect-API'
